const translations = {
    hu: {
        enflag: "Angol zászló",
        huflag: "Magyar zászló",
        home: "Főoldal",
        work: "Munkáim",
        about: "Rólam",
        blog: "Blog",
        welcome: "Hello, <span class='name'>Teodóra</span> vagyok.",
        divider:"Színátmenetes elválasztó vonal",
        shortAbout1: "Kezdő frontend fejlesztő, grafikus és UX designer.",
        shortAbout2: "Szabadidőmben amatőr fotós, könyvmoly és macskásnéni.",
        vector: "Egy vektorkép rólam.",
        myprojects: "Munkáim",
        graphic: "Grafika",
        other: "Egyéb",
        aboutmeTitle: "Néhány szó rólam...",
        aboutmetext1: "<b>Teo</b> vagyok, 29 éves és jelenleg azon dolgozom, hogy megtaláljam azt a munkát, amelyben <strong> hosszú távon fejlődhetek és kiteljesedhetek</strong>.",
        aboutmetext2: "Bár évek óta fizikai munkát végzek, idővel egyértelművé vált számomra, hogy a <b>kreatív, technológiai területek</b> állnak igazán közel hozzám. Ezért kezdtem el komolyabban foglalkozni grafikával és frontend fejlesztéssel.",
        aboutmetext3: "Szabadidőm nagy részét tanulásra és gyakorlásra fordítom – online kurzusokon keresztül és önálló projekteken dolgozva bővítem a tudásom. A maradék időben pedig szívesen olvasok, lehetőleg egy jó kávé mellett.",
        study: "Tanulmányok",
        vasvari: "<span class='blue-text'>- Szegedi SZC Vasvári Pál Gazdasági és Informatikai Technikum</span><br />szoftverfejlesztő és tesztelő képzés (első év befejezve)",
        webler: "<span class='pink-text'>- Webler Oktató Studio </span><br />grafikus OKJ képzés",
        mixer: "<span class='blue-text'>- Best Mixer</span><br />barista, mester barista",
        bethlen: "<span class='pink-text'>- Bethlen Gábor Református Gimnázium</span><br />érettségi",
        extra: "A fentieken túl, több kisebb-nagyobb tanfolyamot is elvégeztem, hogy növeljem a tudásomat. Ebből néhány:",
        bright: "- The Bright Academy - Grafikus és Webdesigner tanfolyam",
        programknowledge:"Program és egyéb ismeretek",
        licence: "- B kategóriás jogosítvány",
        language: "- B2 középszintű angol nyelvvizsga",
        ux: "- UX design alapismeretek",
        dataanalysis: "- adatelemzés alapismeretek",
        graphicdesign: "- grafikai alapismeretek",
        someworksofmine: "Néhány munkám..",
        myprojects1:"Még nem dolgoztam hivatalosan IT területen, és grafikusként is csak rövid időre volt lehetőségem kipróbálni magam, ennek ellenére a digitális alkotás mindig is közel állt hozzám, és az elmúlt években egyre tudatosabban kezdtem el fejleszteni magam ezen a területen.",
        myprojects2:"Fontosnak tartom, hogy ne csak elméletből, hanem gyakorlati projekteken keresztül tanuljak, ezért igyekszem rendszeresen kisebb-nagyobb webes vagy grafikai munkákat készíteni — ezekből válogattam néhányat az alábbiakban.",
        myprojects3:"Ezek a munkák tükrözik, hol tartok most, és azt is, hogy nyitott vagyok a fejlődésre. Nem tökéletesek, de minden egyes darab mögött tanulás, kitartás és érdeklődés áll.",
        myprojects4:"A célom, hogy idővel egy olyan munkakörbe kerülhessek, ahol nemcsak használhatom, hanem tovább is fejleszthetem a megszerzett tudásomat.",
        sayhello: "Üdvözöllek!",
        aboutme1: "Ahogy a főoldalon is olvashattad, a nevem <span class='highlighted-blue'>Teo</span>, 29 éves vagyok, és jelenleg <strong>karrierváltóként az IT világában keresem a helyem</strong>.",
        aboutme2: "A weboldalak iránti érdeklődésem már tinédzserkoromban elkezdődött — akkoriban még a Gportal és a MiLapunk felületein készítettem blogokat és hobbiprojekteket. <br />Érettségi után nem jelentkeztem felsőoktatásba, mivel akkor még nem tudtam pontosan, milyen irányban szeretnék továbbtanulni. Ehelyett fizikai munkát vállaltam, hogy önállóan megéljek, és közben időt adjak magamnak arra, hogy megtaláljam a hozzám illő utat.",
        aboutme3: "Munka mellett több képzést is elvégeztem: <span class='highlighted-blue'>barista</span> és <span class='highlighted-blue'>mesterbarista</span> képesítést szereztem, megszereztem a <span class='highlighted-blue'>jogosítványomat</span>, valamint letettem egy <span class='highlighted-blue'>B2-es angol nyelvvizsgát</span>. Ezen kívül <span class='highlighted-blue'>grafikus OKJ</span> végzettséggel is rendelkezem.",
        aboutme4:"Bár a grafika mindig is közel állt hozzám, egy negatív szakmai tapasztalat miatt egy időre háttérbe szorult. Az elmúlt időszakban viszont azon is dolgozom, hogy <strong>visszanyerjem a kreatív alkotás iránti lelkesedésemet</strong>, és újra örömet találjak a vizuális munkában.",
        aboutme5:"Később ismét nyitottam az informatika felé — egy szoftverfejlesztő és tesztelő képzés során ismerkedtem meg a frontendes alapokkal, amelyek teljesen magukkal ragadtak. Azóta <span class='highlighted-blue'>önállóan, saját tempómban tanulok</span> különböző platformokon, mint a <b>Coursera</b>, a <b>freeCodeCamp</b> és a <b>The Odin Project</b>.",
        aboutme6:"A célom, hogy olyan munkát találjak, ahol nemcsak tovább <span class='highlighted-blue'>fejlődhetek</span>, hanem értéket is teremthetek — akár grafikusként, akár frontend fejlesztőként.",
        shortAboutMe: "Néhány dolog rólam",
        shortAboutMe1:"- Imádok <span class='highlighted-pink'>olvasni</span> - egy jó fantasy, horror vagy krimi bármikor leköt",
        shortAboutMe2:"- Az <span class='highlighted-pink'>ősz</span> a kedvenc évszakom - szeretem az eső illatát, a sárguló leveleket, a Halloween hangulatát és a bekuckózós délutánokat egy jó könyvvel és teával.",
        shortAboutMe3:"- Van <span class='highlighted-pink'>két cicám</span> (Zsebi és Hella), egy <span class='highlighted-pink'>csehszlovák farkaskutyám</span> (Loki) és egy <span class='highlighted-pink'>gabonasiklóm</span> (Mazekeen)",
        shortAboutMe4:"- <span class='highlighted-pink'>Introvertált</span> vagyok - a csend és a nyugalom tölt fel igazán",
        shortAboutMe5:"- Szeretek <span class='highlighted-pink'>utazni</span> - a bakancslistám végtelen hosszú",
        shortAboutMe6:"- Imádom a <span class='highlighted-pink'>lassú reggeleket </span>, amikor van időm egy forró <span class='highlighted-pink'>kávé</span> mellett olvasni",
        shortAboutMe7:"- Hobbiként <span class='highlighted-pink'>nyelveket tanulok</span> – jelenleg az olasz és a német nyelvvel ismerkedem.",
        shortAboutMe8:"- Sokáig szerettem <span class='highlighted-pink'>rajzolni és fotózni</span>, de egy hosszabb kreatív blokk miatt háttérbe szorultak. Most azon dolgozom, hogy újra visszataláljak hozzájuk",
        frCim:"Frontend projektek",
        frontend1:"A <strong class='blue'>BeeWorld</strong> egy pixeles stílusú játék, amelynek elkészítéséhez HTML-t, CSS-t és JavaScriptet használtam.",
        frontend2:"A játék célja, hogy a játékos a kis méhecskét fel-le mozgatva – laptopon a nyílbillentyűk, mobilon az ujj húzásával – összegyűjtsön 20 virágot, miközben elkerüli a mérgező gombákat és a veszélyes darazsakat.",
        frontend3:"A projektet azért hoztam létre, hogy <strong class='blue'>gyakoroljam a JavaScript használatát a gyakorlatban</strong>, valamint hogy fejlesszem a problémamegoldó készségeimet az interaktív elemek megvalósításával. A fejlesztés során számos új kihívással találkoztam, amelyek segítettek elmélyíteni a tudásomat és javítani a kódszervezési technikáimat.",
        frontend4:"Bár a fejlesztés nem volt teljesen önálló – a ChatGPT gyakran segített technikai kérdésekben hoztam létre. Ez egy fontos mérföldkő számomra a tanulás útján.",
        frontend5:"A <strong class='blue'>Purrfect Transformations</strong> egy egyszerű, interaktív projekt, amelyet a JavaScript gyakorlására hoztam létre.",
        frontend6:"A felhasználó egy gombnyomással megnézheti, <strong class='blue'>hogyan néz ki egy cica kiskorában és felnőttként</strong>.",
        frontend7:"A HTML, CSS és JavaScript mellett a <strong class='blue'>Photoshopot</strong> is használtam, hogy a képeket körbevágjam és jobban illeszkedjenek az oldal stílusához.",
        frontend8:"Ez a projekt segített elmélyíteni a DOM-kezeléssel kapcsolatos tudásomat, és öröm volt kombinálni a programozást egy kis grafikai munkával is.",
        frontend9:"Ez az <strong class='blue'>állatos memóriajáték</strong>is a JavaScript gyakorlása céljából készült.",
        frontend10:"A játékos feladata, hogy <strong class='blue'>megtalálja az azonos képpárokat</strong>. A program számolja a próbálkozásokat, és a játék végén egy visszajelző üzenetet is megjelenít.",
        frontend11:"Ez a projekt segített jobban megérteni az eseménykezelést, az állapotkövetést és a DOM-dinamikát.",
        grMunka: "Grafikai munkáim",
        portfolioLink:"Teljes portfólió megtekintése PDF-ben",
        vektorRajzok:"Vektoros rajzok",
        vektRajzSzov:"Szabadidőmben szeretek vektoros illusztrációkat készíteni, főleg állatokról, növényekről és emberekről. Itt néhány kedvenc munkámat gyűjtöttem össze.",
        logokCim:"Logók",
        logokSzov:"Bár elsősorban más grafikai területek állnak hozzám közelebb, időnként logótervezéssel is szívesen foglalkozom.",
        dejavuCim:"Deja vu fesztivál",
        dejavuSzov:"Dolgoztam a Deja vu nevű fesztiválon is, ahol a grafikai anyagok nagy részét én készítettem el – a plakátoktól kezdve a repoharakon és karszalagokon át a közösségi média hirdetésekig. Bevallom, ez a pörgős, nagy volumenű munka nem volt a kedvencem, mégis rengeteget tanultam belőle. Rájöttem, hogy legtöbbet akkor fejlődik az ember, amikor tényleg csinálja.",
        zoldvarosCim:"Zöld város rendezvény",
        zoldvarosSzov:"A Zöldváros rendezvény grafikai anyagait is én készítettem: plakátok, digitális hirdetések és oklevelek formájában. Célom az volt, hogy egységes, friss és környezettudatos arculattal támogassam az eseményt.",
        vegyesCim:"Vegyes grafikák",
        vegyesSzov:"A vegyes munkák részben a kreatív szabadságé a főszerep: Procreate-ben készült illusztrációk,  plakátterv és egy jógaoktatónak készült illusztráció.",
        endSzov:"Ha érdekelnek a korábbi munkáim, a lap tetejére görgetve találsz egy linket a grafikus portfóliómhoz, vagy látogass el <a href='https://www.instagram.com/createo.design/' target='_blank' class='endLink'>instagram oldalamra</a>!"

    },

    en:{
        enflag: "UK flag",
        huflag: "Hungarian flag",
        home: "Home",
        work: "Projects",
        about: "About me",
        blog: "Blog",
        welcome: "Hello, my name is <span class='name'>Teodóra</span>.",
        divider: "Gradient divider",
        shortAbout1: "Aspiring frontend developer with a passion for graphic design and UX.",
        shortAbout2: "In my free time, I'm an amateur photographer, bookworm, and a proud cat lady.",
        vector: "A vector illustration about me.",
        myprojects: "My projects",
        aboutmeTitle:"Some words about me...",
        graphic: "Graphic design",
        other: "Other",
        aboutmetext1: "My name is <b>Teo</b>, I'm 29 years old, and currently working towards finding a job where I can <strong>grow and thrive in the long term</strong>.",
        aboutmetext2: "Although I’ve been doing physical work for years, it has become clear to me over time that I’m truly drawn to <b>creative and technological fields</b>. That’s why I started focusing more seriously on graphic design and frontend development.",
        aboutmetext3: "I spend most of my free time learning and practicing – expanding my skills through online courses and personal projects. The rest of the time, I enjoy reading, preferably with a good cup of coffee.",
        study: "Education",
        vasvari: "<span class='blue-text'>- Szegedi SZC Vasvári Pál Gazdasági és Informatikai Technikum</span><br />software development and testing (first year completed)",
        webler: "<span class='pink-text'>- Webler Oktató Studio </span><br />graphic design OKJ course",
        mixer: "<span class='blue-text'>- Best Mixer</span><br />barista, master barista",
        bethlen: "<span class='pink-text'>- Bethlen Gábor Református Gimnázium</span><br />high school diploma",
        extra: "In addition to the above, I have completed several smaller and larger courses to enhance my knowledge. Here are a few of them:",
        bright: "- The Bright Academy - Graphic and Web design course",
        programknowledge: "Technical and Other Competencies",
        licence: "- Category B driving licence",
        language: "- B2 intermediate level English language exam",
        ux: "- Basic knowledge of UX design",
        dataanalysis: "- Basic knowledge of data analysis",
        graphicdesign: "- Basic knowledge of graphic design",
        someworksofmine: "Some of my work...",
        myprojects1:"I haven't officially worked in the IT field yet, and I only had a short opportunity to try myself as a graphic designer, still, digital creation has always been close to my heart, and in recent years, I’ve started to consciously develop my skills in this area.",
        myprojects2:"I believe it’s important to learn not only from theory but through hands-on projects as well, so I regularly try to create smaller or larger web and graphic works — I've selected a few of these below.",
        myprojects3:"These works reflect where I am right now and also show that I’m open to growth. They’re not perfect, but behind each one is learning, perseverance, and curiosity.",
        myprojects4:"My goal is to eventually find a role where I can not only use but also further develop the knowledge I’ve gained.",
        sayhello: "Welcome!",
        aboutme1: "As you may have read on the homepage, my name is <span class='highlighted-blue'>Teo</span>, I'm 29 years old, and currently, as a <strong>career changer, I'm trying to find my place in the world of IT</strong>.",
        aboutme2: "My interest in websites began back in my teenage years — back then, I created blogs and hobby projects using platforms like Gportal and MiLapunk. <br> After finishing high school, I didn’t apply to university, as I wasn’t sure which path I wanted to pursue. Instead, I took up manual work to support myself independently and give myself time to figure out the right direction.",
        aboutme3: "While working, I completed several trainings: I earned <span class='highlighted-blue'>barista</span> and <span class='highlighted-blue'>master barista</span> certifications, got my <span class='highlighted-blue'>driver’s license</span>, and passed a <span class='highlighted-blue'>B2-level English language exam</span>. I also hold a vocational qualification in <span class='highlighted-blue'>graphic design</span>.",
        aboutme4:"Although graphic design has always been close to my heart, a negative work experience caused me to set it aside for a while. Recently, however, I've been working on <strong>reigniting my passion for creative work</strong> and rediscovering the joy of visual expression.",
        aboutme5:"Later, I turned once again toward IT — during a software development and testing course, I got introduced to frontend basics, which completely captivated me. Since then, <span class='highlighted-blue'>I’ve been learning independently</span> and at my own pace through platforms like <b>Coursera</b>, <b>freeCodeCamp</b> and <b>The Odin Project</b>.",
        aboutme6:"My goal is to find a job where I can not only <span class='highlighted-blue'>continue to grow</span>, but also create value — whether as a graphic designer or as a frontend developer.",
        shortAboutMe:"A few things about me",
        shortAboutMe1:"- I love <span class='highlighted-pink'>reading</span> – a good fantasy, horror, or crime story can always grab my attention",
        shortAboutMe2:"- <span class='highlighted-pink'>Autumn</span> is my favorite season – I enjoy the scent of rain, the yellowing leaves, the Halloween vibe, and cozy afternoons with a good book and a cup of tea",
        shortAboutMe3:"- I have <span class='highlighted-pink'>two cats</span> (Zsebi and Hella), a <span class='highlighted-pink'>Czechoslovakian wolfdog</span> (Loki), and a <span class='highlighted-pink'>corn snake</span> (Mazekeen)",
        shortAboutMe4:"- I’m an <span class='highlighted-pink'>introvert</span> – silence and calm truly recharge me",
        shortAboutMe5:"- I love <span class='highlighted-pink'>traveling</span> – my bucket list is endlessly long",
        shortAboutMe6:"- I adore <span class='highlighted-pink'>slow mornings</span>, when I can read with a <span class='highlighted-pink'>hot coffee</span> in hand",
        shortAboutMe7:"- As a hobby, I <span class='highlighted-pink'>study languages</span> – currently exploring Italian and German",
        shortAboutMe8:"- I used to love <span class='highlighted-pink'>drawing and photography</span>, but a long creative block pushed them into the background. Now I’m working on reconnecting with them again",
        frCim:"Frontend projects",
        frontend1: "The <strong class='blue'>BeeWorld</strong> is a pixel-style game created using HTML, CSS, and JavaScript.",
frontend2: "The goal is to move the little bee up and down — using arrow keys on laptops or swipe gestures on mobile — to collect 20 flowers while avoiding poisonous mushrooms and dangerous wasps.",
frontend3: "I created this project to <strong class='blue'>practice using JavaScript in a hands-on way</strong> and to improve my problem-solving skills by building interactive elements. During development, I encountered many new challenges that helped me deepen my understanding and improve my code organization techniques.",
frontend4: "Although the development wasn't entirely independent — I received a lot of technical help from ChatGPT — this project marks an important milestone for me on my learning journey.",
frontend5: "<strong class='blue'>Purrfect Transformations</strong> is a simple, interactive project I created to practice JavaScript.",
frontend6: "With the click of a button, the user can see <strong class='blue'>how a cat looks as a kitten and as an adult</strong>.",
frontend7: "In addition to HTML, CSS, and JavaScript, I also used <strong class='blue'>Photoshop</strong> to cut out the cat images so they better fit the design of the page.",
frontend8: "This project helped me strengthen my knowledge of DOM manipulation and gave me the joy of combining coding with a bit of graphic design.",
frontend9: "This <strong class='blue'>animal-themed memory game</strong> was also created to practice JavaScript.",
frontend10: "The goal is to <strong class='blue'>find matching image pairs</strong>. The program counts your attempts and displays a feedback message at the end.",
frontend11: "Through this project, I gained a better understanding of event handling, state management, and DOM dynamics.",
  grMunka: "My Graphic Design Projects",
portfolioLink: "View Full Portfolio (PDF)",
  vektorRajzok: "Vector Illustrations",
  vektRajzSzov: "In my free time, I enjoy creating vector illustrations, mainly of animals, plants, and people. Here I've collected a few of my favorite works.",
  logokCim: "Logos",
  logokSzov: "Although I feel closer to other areas of graphic design, I still like to experiment with logo design from time to time.",
  dejavuCim: "Deja Vu Festival",
  dejavuSzov: "I also worked for the Deja Vu festival, where I created most of the graphic materials – from posters to reusable cups, wristbands, and social media ads. Honestly, this fast-paced, large-scale project wasn’t my favorite, but I still learned a lot from it. I realized that you grow the most when you’re actually doing the work.",
  zoldvarosCim: "Green City Event",
  zoldvarosSzov: "I also designed the graphic materials for the Green City event, including posters, digital ads, and certificates. My goal was to support the event with a cohesive, fresh, and eco-friendly visual identity.",
  vegyesCim: "Miscellaneous Graphics",
  vegyesSzov: "In this section, creativity takes the spotlight: Procreate illustrations, poster designs, and an illustration created for a yoga instructor.",
  endSzov: "If you’re interested in seeing more of my previous work, scroll back to the top of the page for a link to my graphic design portfolio, or check out my <a href='https://www.instagram.com/createo.design/' target='_blank' class='endLink'>Instagram page</a>!"
}

}

function setLanguage(language) {
  localStorage.setItem('language', language);

  const trans = translations[language];

  const elements = document.querySelectorAll('[data-id]');

  elements.forEach(function(element) {
    const id = element.getAttribute('data-id');
    if (trans[id]) {
      element.innerHTML = trans[id];
    }
  });
}

window.onload = function() {
  const savedLanguage = localStorage.getItem('language') || 'hu'; // 
  setLanguage(savedLanguage);
};
